import React, { useState, useEffect } from 'react';
import { DollarSign, FileText, CheckCircle, Download, Clock } from 'lucide-react';
import { jsPDF } from 'jspdf';

export default function BillingDashboard({ tenant }) {
    const [billing, setBilling] = useState(null);
    const [loading, setLoading] = useState(true);
    const apiUrl = import.meta.env.VITE_API_URL || '/api';

    const fetchBilling = async () => {
        setLoading(true);
        try {
            const res = await fetch(`${apiUrl}/billing`, { headers: { 'x-tenant-id': tenant?.id || 'filcan' } });
            const data = await res.json();
            setBilling(data);
        } catch {
            setBilling({
                unbilled_leads: [
                    { id: 1, name: 'Jan Marc Santos', score: 92, source: 'CRM', date: 'Today' },
                    { id: 2, name: 'Leo Valdez', score: 98, source: 'Facebook', date: 'Today' },
                    { id: 3, name: 'Piper McLean', score: 85, source: 'Website', date: 'Yesterday' }
                ],
                total_owed: 60, lead_rate: 20,
                history: [
                    { id: 'inv-001', date: '2026-03-01', count: 42, status: 'Verified' },
                    { id: 'inv-002', date: '2026-02-01', count: 31, status: 'Verified' }
                ]
            });
        }
        setLoading(false);
    };

    useEffect(() => {
        fetchBilling();
    }, []);

    const handleMarkBilled = async () => {
        if (!billing?.unbilled_leads?.length) return;
        const ids = billing.unbilled_leads.map(l => l.id);
        try {
            await fetch(`${apiUrl}/leads/mark-billed`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json', 'x-tenant-id': tenant?.id || 'filcan' },
                body: JSON.stringify({ lead_ids: ids })
            });
        } catch { /* demo mode */ }
        setBilling(prev => ({
            ...prev,
            history: [{ id: `inv-${Date.now()}`, date: new Date().toISOString().split('T')[0], count: prev.unbilled_leads.length, status: 'Verified' }, ...prev.history],
            unbilled_leads: [],
            total_owed: 0
        }));
    };

    const generatePDF = () => {
        if (!billing) return;
        const doc = new jsPDF();
        const leads = billing.unbilled_leads || [];

        doc.setFontSize(22);
        doc.setTextColor(0, 51, 102);
        doc.text('REVHUNTER AI', 20, 25);
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text('Performance Volume Audit', 20, 33);

        doc.setDrawColor(0, 51, 102);
        doc.line(20, 38, 190, 38);

        doc.setFontSize(11);
        doc.setTextColor(0);
        doc.text(`Audit Date: ${new Date().toLocaleDateString()}`, 20, 50);
        doc.text(`Dealer: ${tenant?.name || 'FilCan Cars'}`, 20, 58);
        doc.text(`Location: ${tenant?.location || 'Sherwood Park'}`, 20, 66);

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text('Lead Name', 20, 85);
        doc.text('Score', 100, 85);
        doc.text('Source', 130, 85);
        doc.text('Status', 170, 85);
        doc.line(20, 88, 190, 88);

        doc.setTextColor(0);
        leads.forEach((lead, i) => {
            const y = 95 + (i * 8);
            doc.text(lead.name, 20, y);
            doc.text(`${lead.score}%`, 100, y);
            doc.text(lead.source, 130, y);
            doc.text(`QUALIFIED`, 170, y);
        });

        const totalY = 95 + (leads.length * 8) + 10;
        doc.setDrawColor(0, 51, 102);
        doc.line(20, totalY - 3, 190, totalY - 3);
        doc.setFontSize(14);
        doc.setTextColor(217, 32, 39);
        doc.text(`TOTAL QUALIFIED: ${leads.length}`, 130, totalY + 5);

        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text('Generated by RevHunter AI Performance System', 20, 280);

        doc.save(`RevHunter_Audit_${new Date().toISOString().split('T')[0]}.pdf`);
    };

    if (loading) return <div style={{ textAlign: 'center', padding: '60px', color: '#999' }}>Loading volume data...</div>;

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '25px' }}>
            {/* Summary Cards */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px' }}>
                <div style={{ background: 'linear-gradient(135deg, #003366, #001a33)', padding: '25px', borderRadius: '20px', color: 'white' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}><CheckCircle size={20} /> <span style={{ fontSize: '0.8rem', opacity: 0.7 }}>ACTIVE DEPLOYMENT</span></div>
                    <div style={{ fontSize: '2.5rem', fontWeight: '900' }}>PREMIUM</div>
                    <div style={{ fontSize: '0.75rem', opacity: 0.5, marginTop: '5px' }}>Status: Relentless Performance</div>
                </div>
                <div style={{ background: 'white', padding: '25px', borderRadius: '20px', boxShadow: '0 5px 15px rgba(0,0,0,0.05)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px', color: '#D92027' }}><FileText size={20} /> <span style={{ fontSize: '0.8rem', color: '#999' }}>UNAUDITED LEADS</span></div>
                    <div style={{ fontSize: '2.5rem', fontWeight: '900', color: '#003366' }}>{billing?.unbilled_leads?.length || 0}</div>
                    <div style={{ fontSize: '0.75rem', color: '#999', marginTop: '5px' }}>Quality Score ≥ 80%</div>
                </div>
                <div style={{ background: 'white', padding: '25px', borderRadius: '20px', boxShadow: '0 5px 15px rgba(0,0,0,0.05)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px', color: '#00b894' }}><Clock size={20} /> <span style={{ fontSize: '0.8rem', color: '#999' }}>VERIFIED BATCHES</span></div>
                    <div style={{ fontSize: '2.5rem', fontWeight: '900', color: '#003366' }}>{billing?.history?.length || 0}</div>
                    <div style={{ fontSize: '0.75rem', color: '#999', marginTop: '5px' }}>Total verified leads: {billing?.history?.reduce((s, h) => s + h.count, 0) || 0}</div>
                </div>
            </div>

            {/* Unbilled Leads Table */}
            <div style={{ background: 'white', padding: '25px', borderRadius: '20px', boxShadow: '0 5px 15px rgba(0,0,0,0.05)' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
                    <h3 style={{ margin: 0, color: '#003366' }}>UNAUDITED QUALIFIED LEADS</h3>
                    <div style={{ display: 'flex', gap: '10px' }}>
                        <button onClick={generatePDF} disabled={!billing?.unbilled_leads?.length} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 20px', background: '#003366', color: 'white', border: 'none', borderRadius: '10px', fontWeight: 'bold', cursor: 'pointer', opacity: billing?.unbilled_leads?.length ? 1 : 0.5 }}>
                            <Download size={16} /> DOWNLOAD AUDIT
                        </button>
                        <button onClick={handleMarkBilled} disabled={!billing?.unbilled_leads?.length} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 20px', background: '#00b894', color: 'white', border: 'none', borderRadius: '10px', fontWeight: 'bold', cursor: 'pointer', opacity: billing?.unbilled_leads?.length ? 1 : 0.5 }}>
                            <CheckCircle size={16} /> VERIFY ALL
                        </button>
                    </div>
                </div>
                {billing?.unbilled_leads?.length === 0 ? (
                    <div style={{ padding: '40px', textAlign: 'center', color: '#999', border: '2px dashed #eee', borderRadius: '15px' }}>All leads have been verified.</div>
                ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                        <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr 1fr', padding: '10px 15px', fontSize: '0.7rem', fontWeight: 'bold', color: '#999', textTransform: 'uppercase' }}>
                            <span>Lead Name</span><span>Score</span><span>Source</span><span>Status</span>
                        </div>
                        {billing.unbilled_leads.map(lead => (
                            <div key={lead.id} style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr 1fr', padding: '15px', background: '#f8f9fa', borderRadius: '10px', alignItems: 'center' }}>
                                <span style={{ fontWeight: 'bold' }}>{lead.name}</span>
                                <span style={{ color: lead.score >= 90 ? '#00b894' : '#fdcb6e', fontWeight: 'bold' }}>{lead.score}%</span>
                                <span style={{ fontSize: '0.8rem', color: '#666' }}>{lead.source}</span>
                                <span style={{ fontWeight: 'bold', color: '#00b894' }}>QUALIFIED</span>
                            </div>
                        ))}
                    </div>
                )}
            </div>

            {/* Audit History */}
            <div style={{ background: 'white', padding: '25px', borderRadius: '20px', boxShadow: '0 5px 15px rgba(0,0,0,0.05)' }}>
                <h3 style={{ margin: '0 0 20px', color: '#003366', display: 'flex', alignItems: 'center', gap: '10px' }}><Clock size={20} /> AUDIT HISTORY</h3>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                    {(billing?.history || []).map(inv => (
                        <div key={inv.id} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr', padding: '15px', background: '#f8f9fa', borderRadius: '10px', alignItems: 'center' }}>
                            <span style={{ fontWeight: 'bold', color: '#003366' }}>{inv.id}</span>
                            <span style={{ fontSize: '0.85rem', color: '#666' }}>{inv.date}</span>
                            <span style={{ fontWeight: 'bold' }}>{inv.count} leads</span>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                <span style={{ fontWeight: 'bold', color: '#00b894' }}>VERIFIED</span>
                                <span style={{ fontSize: '0.7rem', background: '#e6f4ea', color: '#1e7e34', padding: '3px 8px', borderRadius: '5px' }}>{inv.status}</span>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
